### ISSUE TITLE
GroundStations & TechTree

### ISSUE THREAD

**Issue by 7ranceaddic7** [Y3mo/SETI-RemoteTech#6]
In anticipation of your pending return ...

I'm wondering if there is a way to make the Ground Stations unlock as we progress through the tech tree.  I tried the MechJeb unlock method but that didn't seem to work.

Example:

```
STATION
{
	Guid = 5105f5a9-d628-41c6-ad4b-21154e8fc003
	Name = KSC Mountains
	Latitude = -0.1
	Longitude = -79.72
	Height = 5450
	Body = 1
	MarkColor = 1,0.8,0,0.7
	Antennas
	{
		ANTENNA
		{
			Omni = 1E+06
		}
	}
	unlockTechs = flightControl	// unlock KSC Mountains Dish when flightControl is unlocked in the TechTree.
}
```

**Comment by Y3mo** [comment]
Hey, sorry, took some months off KSP.

I m pretty sure ground station unlocks would require some more coding. With RemoteTech eventually switching to CommNet, that would be something for RT itself after the transition. Since players might want to unlock the stock stations as well.

I m therefore very reluctant to investigate further for my specific config, if there is a chance that it might be done be RemoteTech itself in the future.

Best regards,
Yemo

PS: There are also a lot of bug fixes I have to do, so feature extensions are low priority for me at them moment.

**Comment by 7ranceaddic7** [comment]
Fair enough.  Thanks.
